### ISSUE TITLE
Surface manager script doesn't work correctly

### ISSUE THREAD

**Issue by AmiirAbid** [AmiirAbid/Data_Cleaning_Bots#1]
the issue is in the 4th bot, the **surfaces** get swapped when it's unnecessary (when the **land surface is empty**)

**Comment by YassineAlaya** [comment]
I got you, I will give it a try I guess I found the problem, The swapping issue likely occurs because of this condition:

if (cellD.value is not None and cellE.value is not None) and cellE.value < cellD.value:
    # Swap the values
    cellD.value, cellE.value = cellE.value, cellD.value
    print(cellD.value,'/',cellE.value)
    
This condition checks if both cellD.value and cellE.value are not None, and then it checks if cellE.value is smaller than cellD.value before swapping them. However, when the land surface is empty (i.e., cellE.value is None), the swapping shouldn't happen.
